### ISSUE TITLE
Renovate Get APIs by merging `ConnectionName` RequestBody into URI path

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-spider#907]
**What would you like to be enhanced**
현재 Spider REST API는 `ConnectionName` 을 Request Body를 통해 입력 받고 있으며, GET 메소드의 경우에도 마찬가지 상태.
 - 예: 
    ``` 
    URI: {{ip}}:{{port}}/spider/vmimage   
    Body:
    {
	    "ConnectionName" : "aws-config01"
    }
    ```

GET에 Body를 활용하는 것은, RFC 9110 등의 표준을 준수하지 않는 것이어서, 
Resty, OpenAPI 등 빈번하게 사용하는 라이브러리들을 적극 활용하지 못하게 되는 문제가 있음. (GET인 경우 Body 처리를 무시하거나 거부. 또는 별도의 추가 옵션을 항상 지정해줘야 함. https://github.com/cloud-barista/cb-tumblebug/issues/489)
 - 이는, CB-Spider를 활용하는 모든 클라이언트에 해당
 - 특히, CB-Tumblebug도 Resty 등을 활용하는데 다소 불편함이 있음.

[참고]
 - https://www.baeldung.com/http-get-with-body
 - 다만, GET 수행시 복잡한 쿼리의 입력이 필요한 경우가 있으며, URI 만으로는 가독성이 떨어지는 경우가 있어서, 이 경우 리소스 생성에 해당하지 않는 경우에도 GET 대신 대안으로 POST를 사용하곤 함. REST의 리소스 관점 처리에는 적합하지 않음. 세상의 흐름이라, 특별히 대안은 없는 것으로 판단.)

**Proposed solution**
ConnectionName 과 같이, 간략하고 항상 제공되어야 하는 항목이 있는 경우,
이를 API 개선을 통해, URI Path 에 포함시키고 REST API를 정형화할 수 있을 것으로 보이므로, 개선 검토 필요.

예: 
URI: {{ip}}:{{port}}/spider/vmimage   
--> 
URI: {{ip}}:{{port}}/spider/**connectionname/{ConnectionName}**/vmimage

**Comment by powerkimhub** [comment]
**[Status]**
- ConnectionName의 경우 Query Param을 겸용으로 제공중에 있습니다. 
  - 다음 링크에서 GET-QueryParam 형식 지원 참고:  [CB-Spider User Interface](https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-User-Interface)

<br>

- 현재 ConnectionName 외에 추가적인 인자를 가지고 있어서, 
  - 부득이 GET 호출시 request Body를 사용해야만 하는 API 목록이 다음과 같습니다.
  - GetPriceInfo: https://documenter.getpostman.com/view/24786935/2s9YsT4nNC#bd310e89-784e-443f-8862-719caf5108e0
  - [Dev] Get CSP Resource Info: https://documenter.getpostman.com/view/24786935/2s9YsT4nNC#001b28ca-4304-43cd-a9da-779694d56861
  - [Dev] Get CSP Resource Name: https://documenter.getpostman.com/view/24786935/2s9YsT4nNC#3b3d17e5-cab4-4708-aeda-1697984c7eb9


**[Plan]**
- GetPriceInfo: POST도 겸용으로 추가
- [Dev] Get CSP Resource Info: Query Path도 겸용으로 추가
- [Dev] Get CSP Resource Name: Query Path도 겸용으로 추가
- API documents(postman): ConnectionName에 대한 QueryBody 기본으로 설명을 QueryParam 기본으로 변경

**Comment by powerkimhub** [comment]
- 비표준 형태인 `GET with a request Body`를 포함하는 모든 Rest API를 다음 2가지 타입으로 변경함(since [v0.8.4](https://github.com/cloud-barista/cb-spider/releases/tag/v0.8.4))
  - (Type-1) Query Param으로 변경
  - (Type-2) POST 메소드로 변경
※ Backward Compatibility 위해 기존 GET(with Body) 호출 제공 유지
※ 가급적 Query Param 및 POST 호출 권고


#### [Type-1]
- 자원의 ListXXX 및 GetXXX에 해당하는 대부분의 API들
- Request Body 호출을 기본으로 제공하고,
- 비공식적으로 Query Param 호출을 제공 중에 있었음
- v0.8.4부터 Query Param을 기본으로 제공하고,
- 비공식적으로 하위 호환을 위해  request Body 유지
- 예시: [Dev] GetCSPResourceInfo
  - QueryParam 예시: 권장
  ```
  curl -sX GET "http://localhost:1024/spider/cspresourceinfo/vpc-07bbf1bcd659adcea?ConnectionName=aws-config01&ResourceType=vpc" |json_pp
  ```
  - 기존 Request Body 예시: 비표준, 가급적 지양, 기존 호환 위해 유지
  ```
   curl -sX GET "http://localhost:1024/spider/cspresourceinfo/vpc-07bbf1bcd659adcea" -H 'Content-Type: application/json'  \
          -d '
          {
                  "ConnectionName": "aws-config01",
                  "ResourceType": "vpc" 
          }' | json_pp
  ```


  #### [Type-2]

- 자원의 ListXXX 및 GetXXX에 해당하는 API들 중 복잡한 인자를 포함하는 경우
- 예시: GetPriceInfo, [PMKS] AllClusterList 등 소수의 API
  - POST 호출 예시: 권장
  ```
  curl -sX POST "http://localhost:1024/spider/priceinfo/Compute%20Instance/mercury" \
       -H 'Content-Type: application/json' \
       -d '{
          "ConnectionName": "mock-config-01", 
          "FilterList": [{"Key":"pricingPolicy", "Value":"OnDemand"}
          ]
        }' \
       | jq -r
  ```
  - 기존 GET 호출 예시: 비표준, 가급적 지양, 기존 호환 위해 유지
  ```
  curl -sX GET "http://localhost:1024/spider/priceinfo/Compute%20Instance/mercury" \
       -H 'Content-Type: application/json' \
       -d '{
          "ConnectionName": "mock-config-01", 
          "FilterList": [{"Key":"pricingPolicy", "Value":"OnDemand"}
          ]
        }' \
       | jq -r
  ```


- API documents(postman) v0.8.4부터 적용
  - Before: GET Method 호출시 ConnectionName 등의 변수를 Request Body로 설정
  - After: Query Parameter 설정으로 변경 또는 POST Method로 변경함
  - Ref) [CB-Spider REST API v0.8.4](https://github.com/cloud-barista/cb-spider/wiki/CB-Spider-User-Interface)

**Comment by powerkimhub** [comment]
- Completed in [v0.8.4](https://github.com/cloud-barista/cb-spider/releases/tag/v0.8.4)
